### ISSUE TITLE
Resolve Parameters of Agreement on IDE Configuration

### ISSUE THREAD

**Issue by jayfo** [uwscope/scope-web#3]
I don't think we should have the full IDE configuration in our source control. Note that my initial .gitignore excludes `/.idea/`:

https://github.com/uwscope/scope-web/blob/3b1d19a/.gitignore

But I agree we should have something for the sake of consistency, so we don't repeatedly see the kinds of commits that simply adjust indentation in files like we have in #2. How about an `.editorconfig` file instead?

https://editorconfig.org/

**Comment by jinasuh** [comment]
This is actually standard practice in large development projects: https://github.com/microsoft/vscode/tree/master/.vscode
It ensures consistency across individual dev environments (multiple machines/workspaces per dev) and across the group. In my opinion, everything that is not generated needs to be in the cloud. Since we don't use the same editors, we can have multiple config files checked in. Having a common editorconfig can be useful for new comers to synch to, so I like that idea. But I would also encourage checking in per-editor config files, so you don't have to translate that every time.

**Comment by jayfo** [comment]
Oh interesting. I can "get" the inclusion of multiple IDE configurations as a different philosophy for achieving the same result.

**Comment by jayfo** [comment]
I've renamed the issue to indicate that I think our actual need at this point is therefore to agree on what parameters need to be the same across our editor configurations. Externalizing that in an `.editorconfig` would be nice but seems extremely low priority given the limited number of developers we expect here. Main benefit would be that we might be able to then quickly duplicate that same `.editorconfig` into the other repositories that will emerge with the overall project.
